import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Majbul Rahman
 */
public class home extends javax.swing.JFrame {
           public int z=0;
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        //NewBuyer.setVisible(false);
        //BuyerDetails.setVisible(false);
        //UpdateBuyer.setVisible(false);
        //DeleteBuyer.setVisible(false);
        //NewProduct.setVisible(false);
        //ProductDetails.setVisible(false);
        //UpdateProduct.setVisible(false);
        //DeleteProduct.setVisible(false);
        //Admin.setVisible(false);
        //AdminDetails.setVisible(false);
        //AdminUpdate.setVisible(false);
        //DeleteAdmin.setVisible(false);
        //Seller.setVisible(false);
        //SellerDetails.setVisible(false);
        //SellerUpdate.setVisible(false);
        //DeleteSeller.setVisible(false);
        //Billing.setVisible(false);
        //Logout.setVisible(false);
        //Close.setVisible(false);
        
       // NewB.setVisible(false);
       // BuyerD.setVisible(false);
       // UpdateB.setVisible(false); 
       // DeleteB.setVisible(false);
      //  NewP.setVisible(false);
       // ProductD.setVisible(false);
       // UpdateP.setVisible(false); 
        //DeleteP.setVisible(false);
        //admin.setVisible(false);
        //AdminD.setVisible(false);
        //AdminU.setVisible(false);
        //DeleteA.setVisible(false);
        //seller.setVisible(false);
        //SellerD.setVisible(false);
        //SellerU.setVisible(false);
        //DeleteS.setVisible(false);
        //Bill.setVisible(false);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NewBuyer = new javax.swing.JButton();
        NewB = new javax.swing.JLabel();
        UpdateBuyer = new javax.swing.JButton();
        UpdateB = new javax.swing.JLabel();
        BuyerDetails = new javax.swing.JButton();
        DeleteP = new javax.swing.JLabel();
        DeleteAdmin = new javax.swing.JButton();
        BuyerD = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        NewProduct = new javax.swing.JButton();
        NewP = new javax.swing.JLabel();
        ProductDetails = new javax.swing.JButton();
        ProductD = new javax.swing.JLabel();
        UpdateProduct = new javax.swing.JButton();
        UpdateP = new javax.swing.JLabel();
        DeleteProduct = new javax.swing.JButton();
        DeleteB = new javax.swing.JLabel();
        Billing = new javax.swing.JButton();
        admin = new javax.swing.JLabel();
        Admin = new javax.swing.JButton();
        Bill = new javax.swing.JLabel();
        AdminDetails = new javax.swing.JButton();
        AdminD = new javax.swing.JLabel();
        AdminUpdate = new javax.swing.JButton();
        AdminU = new javax.swing.JLabel();
        Seller = new javax.swing.JButton();
        seller = new javax.swing.JLabel();
        SellerDetails = new javax.swing.JButton();
        SellerUpdate = new javax.swing.JButton();
        SellerD = new javax.swing.JLabel();
        SellerU = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        Close = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        DeleteBuyer = new javax.swing.JButton();
        DeleteA = new javax.swing.JLabel();
        DeleteSeller = new javax.swing.JButton();
        DeleteS = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeeeee.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("HOME PAGES");

        NewBuyer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new buyersss.png"))); // NOI18N
        NewBuyer.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                NewBuyerComponentShown(evt);
            }
        });
        NewBuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBuyerActionPerformed(evt);
            }
        });

        NewB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NewB.setText("   New Buyers");

        UpdateBuyer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updateee.png"))); // NOI18N
        UpdateBuyer.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                UpdateBuyerComponentShown(evt);
            }
        });
        UpdateBuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBuyerActionPerformed(evt);
            }
        });

        UpdateB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UpdateB.setText("  Update Buyers");

        BuyerDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buyers detailsss.png"))); // NOI18N
        BuyerDetails.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                BuyerDetailsComponentShown(evt);
            }
        });
        BuyerDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyerDetailsActionPerformed(evt);
            }
        });

        DeleteP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DeleteP.setText("Delete Products");

        DeleteAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete buyersss.png"))); // NOI18N
        DeleteAdmin.setText(" ");
        DeleteAdmin.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                DeleteAdminComponentShown(evt);
            }
        });
        DeleteAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAdminActionPerformed(evt);
            }
        });

        BuyerD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BuyerD.setText(" Buyers Details");

        Logout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logouttt.png"))); // NOI18N
        Logout.setText("LOG-OUT");
        Logout.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                LogoutComponentShown(evt);
            }
        });
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        NewProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new producttt.png"))); // NOI18N
        NewProduct.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                NewProductComponentShown(evt);
            }
        });
        NewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewProductActionPerformed(evt);
            }
        });

        NewP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NewP.setText("  New Products");

        ProductDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/product Detaills.png"))); // NOI18N
        ProductDetails.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ProductDetailsComponentShown(evt);
            }
        });
        ProductDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductDetailsActionPerformed(evt);
            }
        });

        ProductD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ProductD.setText("Product Details");

        UpdateProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update productss.png"))); // NOI18N
        UpdateProduct.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                UpdateProductComponentShown(evt);
            }
        });
        UpdateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateProductActionPerformed(evt);
            }
        });

        UpdateP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UpdateP.setText("Update Product");

        DeleteProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete producttt.png"))); // NOI18N
        DeleteProduct.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                DeleteProductComponentShown(evt);
            }
        });
        DeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteProductActionPerformed(evt);
            }
        });

        DeleteB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DeleteB.setText("Delete Buyers");

        Billing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billinggg.png"))); // NOI18N
        Billing.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                BillingComponentShown(evt);
            }
        });
        Billing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillingActionPerformed(evt);
            }
        });

        admin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        admin.setText("      Admin ");

        Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin1.png"))); // NOI18N
        Admin.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                AdminComponentShown(evt);
            }
        });
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });

        Bill.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Bill.setText("Billing");

        AdminDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin details.png"))); // NOI18N
        AdminDetails.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                AdminDetailsComponentShown(evt);
            }
        });
        AdminDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminDetailsActionPerformed(evt);
            }
        });

        AdminD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AdminD.setText("  Admin Details");

        AdminUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin Update.png"))); // NOI18N
        AdminUpdate.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                AdminUpdateComponentShown(evt);
            }
        });
        AdminUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminUpdateActionPerformed(evt);
            }
        });

        AdminU.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AdminU.setText("Admin Update");

        Seller.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seller.png"))); // NOI18N
        Seller.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                SellerComponentShown(evt);
            }
        });
        Seller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SellerActionPerformed(evt);
            }
        });

        seller.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        seller.setText("      Seller");

        SellerDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sellerdetails.png"))); // NOI18N
        SellerDetails.setText(" ");
        SellerDetails.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                SellerDetailsComponentShown(evt);
            }
        });
        SellerDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SellerDetailsActionPerformed(evt);
            }
        });

        SellerUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SellerUpdate.png"))); // NOI18N
        SellerUpdate.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                SellerUpdateComponentShown(evt);
            }
        });
        SellerUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SellerUpdateActionPerformed(evt);
            }
        });

        SellerD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SellerD.setText(" Seller Details");

        SellerU.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SellerU.setText("Seller Update");

        Close.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        Close.setText("Close");
        Close.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                CloseComponentShown(evt);
            }
        });
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });

        DeleteBuyer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delt.png"))); // NOI18N
        DeleteBuyer.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                DeleteBuyerComponentShown(evt);
            }
        });
        DeleteBuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBuyerActionPerformed(evt);
            }
        });

        DeleteA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DeleteA.setText("Delete Admin");

        DeleteSeller.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delt.png"))); // NOI18N
        DeleteSeller.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                DeleteSellerComponentShown(evt);
            }
        });
        DeleteSeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteSellerActionPerformed(evt);
            }
        });

        DeleteS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DeleteS.setText("Delete Seller");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Billing, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(Bill)
                        .addGap(196, 196, 196))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                    .addComponent(jSeparator5))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NewBuyer, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NewB))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(BuyerD, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6))
                                    .addComponent(BuyerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NewProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NewP)
                                    .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AdminD, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ProductD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ProductDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(AdminDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(UpdateP)
                                    .addGap(2, 2, 2))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UpdateBuyer, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UpdateB)))
                            .addComponent(UpdateProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(AdminU, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AdminUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Seller, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seller, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(SellerD, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SellerU, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SellerDetails)
                                .addGap(18, 18, 18)
                                .addComponent(SellerUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(DeleteP, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addComponent(DeleteProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DeleteBuyer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(DeleteB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(DeleteA, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(DeleteSeller, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DeleteS, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteAdmin))
                .addGap(61, 61, 61))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Billing, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Bill, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NewBuyer)
                                .addGap(7, 7, 7)
                                .addComponent(NewB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NewProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NewP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(UpdateB, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BuyerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(DeleteBuyer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(UpdateBuyer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BuyerD, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DeleteB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ProductDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UpdateProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DeleteProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ProductD, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UpdateP, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(DeleteP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Admin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(AdminDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AdminD, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AdminU, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SellerDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SellerUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Seller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(DeleteAdmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(AdminUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteA, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DeleteSeller, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SellerD, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SellerU, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(seller, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DeleteS, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 750));

        jPanel2.setBackground(new java.awt.Color(153, 0, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, -40, 850, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewBuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBuyerActionPerformed
        // TODO add your handling code here:
         new NewBuy().setVisible(true);
        
    }//GEN-LAST:event_NewBuyerActionPerformed

    private void BuyerDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyerDetailsActionPerformed
        // TODO add your handling code here:
        new buyersDetails().setVisible(true);
    }//GEN-LAST:event_BuyerDetailsActionPerformed

    private void UpdateBuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBuyerActionPerformed
        // TODO add your handling code here:
        new UpdateBuyer().setVisible(true);
    }//GEN-LAST:event_UpdateBuyerActionPerformed

    private void DeleteAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAdminActionPerformed
        // TODO add your handling code here:
        new DeleteAdmin1().setVisible(true);
    }//GEN-LAST:event_DeleteAdminActionPerformed

    private void NewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewProductActionPerformed
        // TODO add your handling code here:
          new NewProduct().setVisible(true);
    }//GEN-LAST:event_NewProductActionPerformed

    private void ProductDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductDetailsActionPerformed
        // TODO add your handling code here:
        new ProductDetails().setVisible(true);
         
    }//GEN-LAST:event_ProductDetailsActionPerformed

    private void UpdateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateProductActionPerformed
        // TODO add your handling code here:
          new UpdateProduct().setVisible(true);
    }//GEN-LAST:event_UpdateProductActionPerformed

    private void DeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteProductActionPerformed
        // TODO add your handling code here:
        new DeleteProduct().setVisible(true);
    }//GEN-LAST:event_DeleteProductActionPerformed

    private void BillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillingActionPerformed
        // TODO add your handling code here:
         new Billing().setVisible(true);
    }//GEN-LAST:event_BillingActionPerformed

    private void NewBuyerComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_NewBuyerComponentShown
        // TODO add your handling code here:
         try{
            Thread.sleep(250);
            BuyerDetails.setVisible(true);
            BuyerD.setVisible(true);
            }
            catch(Exception e)
            {}
         
    }//GEN-LAST:event_NewBuyerComponentShown

    private void BuyerDetailsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BuyerDetailsComponentShown
        // TODO add your handling code here:
         try{
            Thread.sleep(250);
            UpdateBuyer.setVisible(true);
            UpdateB.setVisible(true);  
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_BuyerDetailsComponentShown

    private void UpdateBuyerComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_UpdateBuyerComponentShown
        // TODO add your handling code here:
        try{
            Thread.sleep(250);
            DeleteAdmin.setVisible(true);
            DeleteB.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_UpdateBuyerComponentShown

    private void DeleteAdminComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_DeleteAdminComponentShown
        // TODO add your handling code here:
         try{
            Thread.sleep(250);
            Seller.setVisible(true);
            seller.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_DeleteAdminComponentShown

    private void NewProductComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_NewProductComponentShown
        // TODO add your handling code here:
        try{
            Thread.sleep(250);
            ProductDetails.setVisible(true);
            ProductD.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_NewProductComponentShown

    private void ProductDetailsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ProductDetailsComponentShown
        // TODO add your handling code here:
         try{
            Thread.sleep(250);
            UpdateProduct.setVisible(true);
            UpdateP.setVisible(true);  
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_ProductDetailsComponentShown

    private void UpdateProductComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_UpdateProductComponentShown
        // TODO add your handling code here:
        try{
            Thread.sleep(250);
            DeleteProduct.setVisible(true);
            DeleteP.setVisible(true); 
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_UpdateProductComponentShown

    private void DeleteProductComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_DeleteProductComponentShown
        // TODO add your handling code here:
          try{
            Thread.sleep(250);
            Admin.setVisible(true);
            admin.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_DeleteProductComponentShown

    private void BillingComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BillingComponentShown
        // TODO add your handling code here:
         try{
            Thread.sleep(250);
            Logout.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_BillingComponentShown

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"DO you really want to Logout","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            setVisible(false);
            new Login1().setVisible(true);

        }
    }//GEN-LAST:event_LogoutActionPerformed

    private void LogoutComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_LogoutComponentShown
        // TODO add your handling code here:
        try{
            Thread.sleep(250);
            Close.setVisible(true);
            z=1;
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_LogoutComponentShown

    private void CloseComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_CloseComponentShown
        // TODO add your handling code here:
   
    }//GEN-LAST:event_CloseComponentShown

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"DO you really want to close Application","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_CloseActionPerformed

    private void AdminComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_AdminComponentShown
        // TODO add your handling code here:
         try{
            Thread.sleep(250);
            AdminDetails.setVisible(true);
            AdminD.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_AdminComponentShown

    private void AdminDetailsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_AdminDetailsComponentShown
        // TODO add your handling code here:
         try{
            Thread.sleep(250);
            AdminUpdate.setVisible(true);
            AdminU.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_AdminDetailsComponentShown

    private void AdminUpdateComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_AdminUpdateComponentShown
        // TODO add your handling code here:
         try{
            Thread.sleep(250);
            DeleteAdmin.setVisible(true);
            DeleteA.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_AdminUpdateComponentShown

    private void SellerComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_SellerComponentShown
        // TODO add your handling code here:
         try{
            Thread.sleep(250);
            SellerDetails.setVisible(true);
            SellerD.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_SellerComponentShown

    private void SellerDetailsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_SellerDetailsComponentShown
        // TODO add your handling code here:
         try{
            Thread.sleep(250);
            SellerUpdate.setVisible(true);
            SellerU.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_SellerDetailsComponentShown

    private void SellerUpdateComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_SellerUpdateComponentShown
        // TODO add your handling code here:
        try{
            Thread.sleep(250);
            DeleteSeller.setVisible(true);
            DeleteS.setVisible(true);
            }
            catch(Exception e)
            {} 
    }//GEN-LAST:event_SellerUpdateComponentShown

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
        // TODO add your handling code here:
        new Admin().setVisible(true);
    }//GEN-LAST:event_AdminActionPerformed

    private void AdminDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminDetailsActionPerformed
        // TODO add your handling code here:
           new AdminDetails().setVisible(true);
    }//GEN-LAST:event_AdminDetailsActionPerformed

    private void AdminUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminUpdateActionPerformed
        // TODO add your handling code here:
           new UpdateAdmin1().setVisible(true);
    }//GEN-LAST:event_AdminUpdateActionPerformed

    private void SellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SellerActionPerformed
        // TODO add your handling code here:
        new Seller1().setVisible(true);
    }//GEN-LAST:event_SellerActionPerformed

    private void SellerDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SellerDetailsActionPerformed
        // TODO add your handling code here:
        new SellerDetails().setVisible(true);
    }//GEN-LAST:event_SellerDetailsActionPerformed

    private void SellerUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SellerUpdateActionPerformed
        // TODO add your handling code here:
         new SellerUpdate1().setVisible(true);
    }//GEN-LAST:event_SellerUpdateActionPerformed

    private void DeleteBuyerComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_DeleteBuyerComponentShown
        // TODO add your handling code here:
        try{
            Thread.sleep(250);
            NewProduct.setVisible(true);
            NewP.setVisible(true); 
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_DeleteBuyerComponentShown

    private void DeleteBuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBuyerActionPerformed
        // TODO add your handling code here:
        new DeleteBuyer().setVisible(true);
    }//GEN-LAST:event_DeleteBuyerActionPerformed

    private void DeleteSellerComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_DeleteSellerComponentShown
        // TODO add your handling code here:
        try{
            Thread.sleep(250);
            Billing.setVisible(true);
            Bill.setVisible(true);
            }
            catch(Exception e)
            {}
    }//GEN-LAST:event_DeleteSellerComponentShown

    private void DeleteSellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteSellerActionPerformed
        // TODO add your handling code here:
        new DeleteSeller1().setVisible(true);
    }//GEN-LAST:event_DeleteSellerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin;
    private javax.swing.JLabel AdminD;
    private javax.swing.JButton AdminDetails;
    private javax.swing.JLabel AdminU;
    private javax.swing.JButton AdminUpdate;
    private javax.swing.JLabel Bill;
    private javax.swing.JButton Billing;
    private javax.swing.JLabel BuyerD;
    private javax.swing.JButton BuyerDetails;
    private javax.swing.JButton Close;
    private javax.swing.JLabel DeleteA;
    private javax.swing.JButton DeleteAdmin;
    private javax.swing.JLabel DeleteB;
    private javax.swing.JButton DeleteBuyer;
    private javax.swing.JLabel DeleteP;
    private javax.swing.JButton DeleteProduct;
    private javax.swing.JLabel DeleteS;
    private javax.swing.JButton DeleteSeller;
    private javax.swing.JButton Logout;
    private javax.swing.JLabel NewB;
    private javax.swing.JButton NewBuyer;
    private javax.swing.JLabel NewP;
    private javax.swing.JButton NewProduct;
    private javax.swing.JLabel ProductD;
    private javax.swing.JButton ProductDetails;
    private javax.swing.JButton Seller;
    private javax.swing.JLabel SellerD;
    private javax.swing.JButton SellerDetails;
    private javax.swing.JLabel SellerU;
    private javax.swing.JButton SellerUpdate;
    private javax.swing.JLabel UpdateB;
    private javax.swing.JButton UpdateBuyer;
    private javax.swing.JLabel UpdateP;
    private javax.swing.JButton UpdateProduct;
    private javax.swing.JLabel admin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel seller;
    // End of variables declaration//GEN-END:variables
}
